### ISSUE TITLE
How can I use these?

### ISSUE THREAD

**Issue by KerkFleet** [nikitastupin/solc#2]
Hi there,

I'm trying to run brownie on an Nvidia Jetson Nano, which runs ARM64 architecture. I didn't realize that it would be so difficult to compile solidity on this architecture. I've tried nearly every option I can think of with no luck. I just stumble across this, and am hoping to be able to use these binaries for this. Is it possible to do so? If so how can I go about doing it? My knowledge is limited when it comes to this lower level installation. 

If it is possible, here's what I've tried already:
I downloaded the version that I wanted to use and placed it in my ~/.solc/ folder since that's where brownie looks for the compiler. I opened the permissions up on the file, and then attempted to compile. I received this error message as a result:
CalledProcessError: Command '['/home/<user>/.solcx/solc-v0.8.13', '--version']' returned non-zero exit status 1.

If I'm not able to use them for this, do you have any recommendation on how I can compile solidity from the brownie framework on this architecture?

**Comment by nikitastupin** [comment]
Hi @KerkFleet,

Could you try to download a solc binary from this repo (for example, `solc-v0.8.13`), make it executable `chmod +x solc-v0.8.13`, and run it with `./solc-v0.8.13`.

What's the output in this case? What's the status code?

Thanks for reaching out!

**Comment by KerkFleet** [comment]
Thanks a ton for the reply! Well, giving that a try, I do get an error message:

bash: ./solc-v0.8.13: cannot execute binary file: Exec format error

Does this mean I'm unable to run it on this architecture? I do see your repo says it's for aarch64, which I believe is what I have here, but certainly there are some things I don't understand with how it works.

**Comment by nikitastupin** [comment]
I'm glad that it worked for you 😃 Though, it's quite strange that `solc-v0.8.11` executed with an error and `solc-v0.8.13` executed successfully 🤷

In my experience the `bash: ./solc-v0.8.11: cannot execute binary file: Exec format error` error occurs when binary's architecture doesn't match CPU architecture. On my aarch64 Ubuntu VM both binaries run well. My best guess is that I've produced these binaries on different machines with different compiler versions so some things might got different.

I'd be happy to dig deeper into it if you run and share the output of the following script:

```bash
#!/bin/bash

versions="$(curl -sL https://github.com/nikitastupin/solc/raw/main/linux/aarch64/list.json | jq -r '.builds[].version' | sort)"

echo "$versions" | while read ver; do
  bin="solc-v$ver"

  echo "testing: $bin"

  curl -sO "https://raw.githubusercontent.com/nikitastupin/solc/main/linux/aarch64/$bin"
  chmod +x "$bin"
  "./$bin" --version
  rm "$bin"
done
```

Otherwise feel free to close the issue as the original problem seems to be solved.

**Comment by KerkFleet** [comment]
I am on crunch time with some projects at the moment and am not able to just yet. I'm not sure how long I will have the device in my hands. If I get a chance to run the script above, I would certainly be happy to help you out there. For now, I will close this issue, and open a new one related to that problem if I get the chance. Thanks again for your help here! This repo made a lot more possible for me!
